models/AddStock.php
<?php

namespace app\models;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "add_stock".
 *
 * @property int $add_id
 * @property int $stock_id
 * @property int $item_id
 * @property string $add_date
 * @property int $qty
 * @property int $user_id
 * @property string|null $add_date
 */
class AddStock extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    const PENDING = '1';
    const COMPLETE = '2';

    public static function tableName()
    {
        return 'add_stock';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['stock_id', 'item_id', 'add_date', 'qty', 'user_id'], 'required'],
            [['stock_id', 'item_id', 'qty', 'user_id'], 'integer'],
            [['add_date'], 'safe'],
            [['status_id'],'string', 'max' => 1],

        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'add_id' => 'ลำดับที่',
            'stock_id' => 'คลัง',
            'item_id' => 'รายการ',
            'add_date' => 'วันที่',
            'qty' => 'จำนวน',
            'user_id' => 'ผู้บัทึก',
            'status_id' => 'สถานะการรับเข้าคลัง',
        ];
    }

    public function getItem()
    {
        return $this->hasOne(Item::className(), ['item_id' => 'item_id']);
    }

    public function getStock()
    {
        return $this->hasOne(Stock::className(), ['stock_id' => 'stock_id']);
    }

    public function getUser()
    {
        return $this->hasOne(Profile::className(), ['user_id' => 'user_id']);
    }

    public static function itemsAlias($key)
    {

        $items = [
            'status' => [
                self::PENDING => 'รอรับ',
                self::COMPLETE => 'รับเข้า',
            ],
        ];
        return ArrayHelper::getValue($items, $key, []);
        //return array_key_exists($key, $items) ? $items[$key] : [];
    }

    public function getItemStatus()
    {
        return self::itemsAlias('status');
    }

    public function getStatusName(){
        return ArrayHelper::getValue($this->getItemSex(),$this->status_id);
    }

}

controllers/AddstockController.php
<?php

namespace app\controllers;

use Yii;
use app\models\AddStock;
use app\models\AddStockSearch;
use app\models\Inventory;
use IntlChar;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * AddstockController implements the CRUD actions for AddStock model.
 */
class AddstockController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all AddStock models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new AddStockSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        if(Yii::$app->user->identity->role == 2 ) {
            $dataProvider->query->where(['stock_id' => Yii::$app->user->identity->profile->stock_id]);
        }

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single AddStock model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new AddStock model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($inv_id)
    {
        $inv = Inventory::findOne($inv_id);
        $model = new AddStock();
        $model->item_id = $inv->item_id;
        $model->user_id = Yii::$app->user->identity->id;
        $model->stock_id = $inv->stock_id;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $inv->remain = $inv->remain + $model->qty;
            $inv->save();
            return $this->redirect(['inventory/index']);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing AddStock model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->add_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionRecieve($id)
    {
        $model = $this->findModel($id);
        $model->status_id = '2';

        if ($model->save()) {
            $inv = Inventory::find()->where(['item_id'=> $model->item_id,'stock_id'=>$model->stock_id])->one();
            $inv->remain = $inv->remain + $model->qty;
            $inv->save();
            return $this->redirect(['index']);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing AddStock model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the AddStock model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return AddStock the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = AddStock::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/addstock/_form.php
<?php

use yii\bootstrap4\Html;
use yii\bootstrap4\ActiveForm;
use kartik\date\DatePicker;

/* @var $this yii\web\View */
/* @var $model app\models\AddStock */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="add-stock-form">

    <?php $form = ActiveForm::begin(); ?>
    <div class="row">
        <div class="col-md-4">
            <?= $form->field($model, 'add_date')->widget(
                DatePicker::ClassName(),
                [
                    'name' => 'วันที่รับเข้าคลัง',
                    'type' => DatePicker::TYPE_COMPONENT_APPEND,
                    'options' => ['placeholder' => 'ระบุวัน'],
                    'pluginOptions' => [
                        'format' => 'yyyy-mm-dd',
                        'todayHighlight' => true
                    ]
                ]
            );
            ?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'qty')->textInput() ?>
        </div>
    </div>
    <div class="form-group">
        <?= Html::submitButton('รับเข้าคลัง', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/addstock/_search.php
<?php

use yii\bootstrap4\Html;
use yii\bootstrap4\ActiveForm;
use yii\helpers\ArrayHelper;
use kartik\date\DatePicker;
use kartik\icons\Icon;
Icon::map($this);

/* @var $this yii\web\View */
/* @var $model app\models\InventorySearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="add-stock-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>
    <div class="row">
        <div class="col-md-4">
            <?= $form->field($model, 'item_name')->textInput(['placeholder' => 'ค้นหาด้วยชื่อ...'])->label(false) ?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'add_date')->widget(
                DatePicker::ClassName(),
                [
                    'name' => 'วันที่รับเข้าคลัง',
                    'type' => DatePicker::TYPE_COMPONENT_APPEND,
                    'options' => ['placeholder' => 'ค้นหาจากวันที่รับเข้าคลัง'],
                    'pluginOptions' => [
                        'format' => 'yyyy-mm-dd',
                        'todayHighlight' => true
                    ]
                ]
            )->label(false);
            ?>
        </div>
        <div class="col-md-4">
            <?= Html::submitButton(Icon::show('fa fa-search').' ค้นหา', ['class' => 'btn btn-primary']) ?>
        </div>
    </div>

    <?php //= $form->field($model, 'remain') 
    ?>

    <?php ActiveForm::end(); ?>
    
</div>

views/addstock/create.php
<?php

use yii\bootstrap4\Html;

/* @var $this yii\web\View */
/* @var $model app\models\AddStock */

$this->title = 'รับเข้าคลัง';
$this->params['breadcrumbs'][] = ['label' => 'ทะเบียนรับเข้าคลัง', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="add-stock-create">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/addstock/index.php
<?php

use app\models\Inventory;
use yii\bootstrap4\Html;
// use yii\grid\GridView;
use kartik\grid\GridView;
use kartik\icons\Icon;
Icon::map($this);

/* @var $this yii\web\View */
/* @var $searchModel app\models\AddStockSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'ทะเบียนรับเข้าคลัง';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="add-stock-index">

    <?= $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'panel' => [
            'heading' => "ทะเบียนรับเข้าคลัง",
            'before' => ' ',
            'type' => \kartik\grid\GridView::TYPE_SUCCESS,
        ],
        //'filterModel' => $searchModel,
        'columns' => [
            'add_id',
            [
                'attribute' => 'stock_id',
                'headerOptions' => ['style' => 'width:20%'],
                'value' => function($model){
                    return $model->stock->stock_name;
                }
            ],
            [
                'attribute' => 'item_id',
                'headerOptions' => ['style' => 'width:30%'],
                'value' => function($model){
                    return $model->item->item_name;
                }
            ],
            [
                'attribute' => 'qty',
                'contentOptions'=> ['style'=>'text-align:center;'],
                'value' => function($model){
                    return number_format($model->qty);
                }
            ],
            [
                'attribute' => 'user_id',
                'contentOptions'=> ['style'=>'text-align:center;'],
                'value' => function($model){
                    return $model->user->fullname;
                }
            ],
            [
                'attribute' => 'add_date',
                'contentOptions'=> ['style'=>'text-align:center;'],
                'value' => function($model){
                    return Inventory::getThaiDate($model->add_date);
                }
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'header' => 'สถานะ',
                'options' => ['style' => 'width:50px;'],
                'buttonOptions' => ['class' => 'btn btn-primary btn-sm'],
                'template' => '{recieve}',
                'buttons' => [
                    'recieve' => function ($url, $model, $key) {
                        return $model->status_id == 1 ? Html::a(Icon::show('fa fa-cart-plus'), ['addstock/recieve', 'id' => $model->add_id], ['class' => 'btn btn-success', 'style' => ['width' => '50px']]):'&#x2714;';
                    }
                ]
            ],
        ],
    ]); ?>


</div>

views/addstock/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\AddStock */

$this->title = 'Update Add Stock: ' . $model->add_id;
$this->params['breadcrumbs'][] = ['label' => 'Add Stocks', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->add_id, 'url' => ['view', 'id' => $model->add_id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="add-stock-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/addstock/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\AddStock */

$this->title = $model->add_id;
$this->params['breadcrumbs'][] = ['label' => 'Add Stocks', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="add-stock-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->add_id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->add_id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'add_id',
            'stock_id',
            'item_id',
            'add_date',
            'qty',
            'user_id',
        ],
    ]) ?>

</div>