models/Inventory.php
<?php

namespace app\models;


use Yii;
use DateTime;
/**
 * This is the model class for table "inventory".
 *
 * @property int $inventory_id
 * @property int $item_id
 * @property int $stock_id
 * @property int|null $remain
 * @property int|null $user_id
 * @property string|null $d_update
 */
class Inventory extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'inventory';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['item_id', 'stock_id'], 'required'],
            [['item_id', 'stock_id', 'remain', 'user_id'], 'integer'],
            [['d_update'], 'safe'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'inventory_id' => 'เลขที่',
            'item_id' => 'รายการ',
            'stock_id' => 'คลัง',
            'remain' => 'คงเหลือ',
            'user_id' => 'ผู้ปรับปรุง',
            'd_update' => 'ปรับปรุงล่าสุด',
        ];
    }

    public function getItem()
    {
        return $this->hasOne(Item::className(), ['item_id' => 'item_id']);
    }

    public function getUser()
    {
        return $this->hasOne(Profile::className(), ['user_id' => 'user_id']);
    }

    public static function getThaiDate($date)
    {
        $month = array("01"=>"ม.ค.","02"=>"ก.พ","03"=>"มี.ค.","04"=>"เม.ย.","05"=>"พ.ค.","06"=>"มิ.ย.","07"=>"ก.ค.","08"=>"ส.ค.","09"=>"ก.ย.","10"=>"ต.ค.","11"=>"พ.ย.","12"=>"ธ.ค.");
        if($date){
            $visit = new DateTime($date);
            $d = $visit->format('j');
            $m = $month[$visit->format('m')];
            $y = $visit->format('Y')+543;
            $result = $d.' '.$m.' '.$y;    
        } else {
            $result = 'ไม่ระบุ';
        }
        return $result;
    }

}

controllers/DespendController.php
<?php

namespace app\controllers;

use app\models\AddStock;
use Yii;
use app\models\Despend;
use app\models\DespendSearch;
use app\models\Req;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\Inventory;

/**
 * DespendController implements the CRUD actions for Despend model.
 */
class DespendController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Despend models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new DespendSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        if(Yii::$app->user->identity->role == 2 ) {
            $dataProvider->query->where(['stock_id' => Yii::$app->user->identity->profile->stock_id]);
        }

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Despend model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Despend model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($req_id)
    {
        $req = Req::findOne($req_id);

        $model = new Despend();
        $model->stock_id = Yii::$app->user->identity->profile->stock_id;
        if ($req) {
            $model->item_id = $req->item_id;
            $model->to_stock = $req->stock_id;
            $model->req_id = $req->req_id;
            $model->qty = $req->qty;
            $inv = Inventory::find()->where(['item_id' => $model->item_id, 'stock_id' => $model->stock_id])->one();
        }

        if ($model->load(Yii::$app->request->post())) {
            $inv = Inventory::find()->where(['item_id' => $model->item_id, 'stock_id' => $model->stock_id])->one();
            if ($inv->remain >= $model->qty) {
                $model->status_id = '2';
                if ($model->save()) {
                    $inv->remain = $inv->remain - $model->qty;
                    $inv->save();

                    $add = new AddStock();
                    $add->stock_id = $model->to_stock;
                    $add->item_id = $model->item_id;
                    $add->add_date = $model->despend_date;
                    $add->user_id = Yii::$app->user->identity->id;
                    $add->qty = $model->qty;
                    $add->status_id = '1';
                    $add->save();

                    return $this->redirect(['req/index']);
                }
            } else {
                $model->qty = $inv->remain;
                $model->status_id = '4';
                if ($model->save()) {
                    $inv->remain = 0;
                    $inv->save();

                    $add = new AddStock();
                    $add->stock_id = $model->to_stock;
                    $add->item_id = $model->item_id;
                    $add->add_date = $model->despend_date;
                    $add->user_id = Yii::$app->user->identity->id;
                    $add->qty = $model->qty;
                    $add->status_id = '1';
                    $add->save();

                    return $this->redirect(['req/index']);
                }
            }
        }

        return $this->render('create', [
            'model' => $model,
            'inv' => $inv,
        ]);
    }

    public function actionDispend($inv_id)
    {
        $inv = Inventory::findOne($inv_id);

        $model = new Despend();
        $model->stock_id = Yii::$app->user->identity->profile->stock_id;
        $model->item_id = $inv->item_id;
        $model->to_stock = 0;
        $model->req_id = 0;

        if ($model->load(Yii::$app->request->post())) {
            if ($inv->remain >= $model->qty) {
                $model->status_id = '2';
                if ($model->save()) {
                    $inv->remain = $inv->remain - $model->qty;
                    $inv->save();

                    return $this->redirect(['inventory/index']);
                }
            } else {
                $model->qty = $inv->remain;
                $model->status_id = '4';
                if ($model->save()) {
                    $inv->remain = 0;
                    $inv->save();

                    return $this->redirect(['inventory/index']);
                }
            }
        }

        return $this->render('update', [
            'model' => $model,
            'inv' => $inv,
        ]);
    }


    /**
     * Updates an existing Despend model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->despend_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Despend model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Despend model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Despend the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Despend::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/ItemController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Item;
use app\models\ItemSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ItemController implements the CRUD actions for Item model.
 */
class ItemController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Item models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ItemSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Item model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Item model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Item();
        $stock_id = Yii::$app->user->identity->profile->stock_id; 

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['inventory/create', 'item_id' => $model->item_id,'stock_id'=>$stock_id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Item model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->item_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Item model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Item model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Item the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Item::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/ReqController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Req;
use app\models\ReqSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ReqController implements the CRUD actions for Req model.
 */
class ReqController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Req models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ReqSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        if(Yii::$app->user->identity->role == 2){
            $dataProvider->query->where(['stock_id'=>Yii::$app->user->identity->profile->stock_id]);
        }

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Req model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Req model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($item_id)
    {
        $model = new Req();
        $model->item_id = $item_id;
        $model->stock_id = Yii::$app->user->identity->profile->stock_id;
        $model->status_id = '1';

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['inventory/list', 'id' => $model->stock_id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Req model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->req_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Req model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Req model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Req the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Req::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/inventory/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Inventory */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="inventory-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'inventory_id')->textInput() ?>

    <?= $form->field($model, 'item_id')->textInput() ?>

    <?= $form->field($model, 'stock_id')->textInput() ?>

    <?= $form->field($model, 'remain')->textInput() ?>

    <?= $form->field($model, 'user_id')->textInput() ?>

    <?= $form->field($model, 'd_update')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/inventory/_form_new.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Inventory */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="inventory-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'remain')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/inventory/_search.php
<?php

use yii\bootstrap4\Html;
use yii\bootstrap4\ActiveForm;
use app\models\Stock;
use yii\helpers\ArrayHelper;
use kartik\icons\Icon;
Icon::map($this);
$stock = ArrayHelper::map(Stock::find()->all(), 'stock_id', 'stock_name');
/* @var $this yii\web\View */
/* @var $model app\models\InventorySearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="inventory-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>
    <div class="row">
        <div class="col-md-4">
            <?= $form->field($model, 'item_name')->textInput(['placeholder' => 'ค้นหาด้วยชื่อ...'])->label(false) ?>
        </div>
        <div class="col-md-4">
            <?= Yii::$app->user->identity->role == 1 ? $form->field($model, 'stock_id')->dropDownList($stock, ['prompt' => 'ค้นหาจากคลัง...',])->label(false):'' ?>
        </div>
        <div class="col-md-4">
            <?= Html::submitButton(Icon::show('fa fa-search').' ค้นหา', ['class' => 'btn btn-primary']) ?>
        </div>
    </div>

    <?php //= $form->field($model, 'remain') 
    ?>

    <?php ActiveForm::end(); ?>
    
</div>

views/inventory/_search_list.php
<?php

use yii\bootstrap4\Html;
use yii\bootstrap4\ActiveForm;
use app\models\Stock;
use yii\helpers\ArrayHelper;
use kartik\icons\Icon;
Icon::map($this);
$stock = ArrayHelper::map(Stock::find()->all(), 'stock_id', 'stock_name');
/* @var $this yii\web\View */
/* @var $model app\models\InventorySearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="inventory-search">

    <?php $form = ActiveForm::begin([
        'action' => ['list','id'=>$id],
        'method' => 'get',
    ]); ?>
    <div class="row">
        <div class="col-md-4">
            <?= $form->field($model, 'item_name')->textInput(['placeholder' => 'ค้นหาด้วยชื่อ...'])->label(false) ?>
        </div>
        <div class="col-md-4">
            <?= Html::submitButton(Icon::show('fa fa-search').' ค้นหา', ['class' => 'btn btn-primary']) ?>
        </div>
    </div>

    <?php //= $form->field($model, 'remain') 
    ?>

    <?php ActiveForm::end(); ?>
    
</div>

views/inventory/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Inventory */

$this->title = 'Create Inventory';
$this->params['breadcrumbs'][] = ['label' => 'Inventories', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="inventory-create">

    <?= $this->render('_form_new', [
        'model' => $model,
    ]) ?>

</div>

views/inventory/index.php
<?php

use yii\bootstrap4\Html;
// use yii\grid\GridView;
use kartik\grid\GridView;
use kartik\icons\Icon;
Icon::map($this);

/* @var $this yii\web\View */
/* @var $searchModel app\models\InventorySearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'รายการคงคลัง';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="inventory-index">

    <p>
        <?= Yii::$app->user->identity->role == 1 ? Html::a('เพิ่มรายการ', ['item/create'], ['class' => 'btn btn-success']):'' ?>
    </p>

    <?= $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'panel' => [
            'heading' => "รายการเวชภัณฑ์มิใช่ยา",
            'before' => ' ',
            'type' => \kartik\grid\GridView::TYPE_SUCCESS,
        ],
        // 'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            [
                'class' => 'yii\grid\ActionColumn',
                'header' => 'รับเข้าคลัง',
                'options' => ['style' => 'width:50px;'],
                'buttonOptions' => ['class' => 'btn btn-primary btn-sm'],
                'template' => '{add}',
                'buttons' => [
                    'add' => function ($url, $model, $key) {
                        return Yii::$app->user->identity->role < 3 ? Html::a(Icon::show('fa fa-cart-plus'), ['addstock/create', 'inv_id' => $model->inventory_id], ['class' => 'btn btn-success', 'style' => ['width' => '50px']]):'';
                    }
                ]
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'header' => 'ขอเบิก',
                'options' => ['style' => 'width:50px;'],
                'buttonOptions' => ['class' => 'btn btn-primary btn-sm'],
                'template' => '{req}',
                'buttons' => [
                    'req' => function ($url, $model, $key) {
                        return Html::a(Icon::show('fa fa-list'), ['req/create', 'item_id' => $model->item_id], ['class' => 'btn btn-primary', 'style' => ['width' => '50px']]);
                    }
                ]
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'header' => 'ตัดจ่าย',
                'options' => ['style' => 'width:50px;'],
                'buttonOptions' => ['class' => 'btn btn-primary btn-sm'],
                'template' => '{despend}',
                'buttons' => [
                    'despend' => function ($url, $model, $key) {
                        return Html::a(Icon::show('fa fa-dolly'), ['despend/dispend', 'inv_id' => $model->inventory_id], ['class' => 'btn btn-danger', 'style' => ['width' => '50px']]);
                    }
                ]
            ],
            [
                'attribute' => 'item_id',
                'headerOptions' => ['style' => 'width:30%'],
                'value' => function($model){
                    return $model->item->item_name;
                }
            ],
            [
                'attribute' => 'remain',
//                'headerOptions' => ['style' => 'align:right'],
                'contentOptions'=> ['style'=>'text-align:center;'],
                'value' => function($model){
                    return number_format($model->remain);
                }
                //'format' => 'raw',
            ],
            //'inventory_id',
            //'item.item_name',
            //'stock_id',
            //'remain',
            [
                'attribute' => 'user_id',
                'contentOptions'=> ['style'=>'text-align:center;'],
                'value' => function($model){
                    return $model->user->fullname;
                }
            ],
            [
                'attribute' => 'd_update',
                'contentOptions'=> ['style'=>'text-align:center;'],
                'value' => function($model){
                    return $model->getThaiDate($model->d_update);
                }
            ],
            //'d_update',

            // ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>


</div>

views/inventory/list.php
<?php

use yii\bootstrap4\Html;
use kartik\grid\GridView;
use kartik\icons\Icon;
Icon::map($this);

/* @var $this yii\web\View */
/* @var $searchModel app\models\InventorySearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
        
$this->title = $stock->stock_name;
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="inventory-list">

    <?= $this->render('_search_list', ['model' => $searchModel,'id'=>$stock->stock_id]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'panel' => [
            'heading' => "รายการเวชภัณฑ์มิใช่ยา",
            'before' => ' ',
            'type' => \kartik\grid\GridView::TYPE_SUCCESS,
        ],
        // 'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            [
                'attribute' => 'item_id',
                'headerOptions' => ['style' => 'width:40%'],
                'value' => function($model){
                    return $model->item->item_name;
                }
            ],
            [
                'attribute' => 'remain',
                'contentOptions'=> ['style'=>'text-align:center;'],
                'value' => function($model){
                    return number_format($model->remain);
                }
            ],
            [
                'attribute' => 'user_id',
                'contentOptions'=> ['style'=>'text-align:center;'],
                'value' => function($model){
                    return $model->user->fullname;
                }
            ],
            [
                'attribute' => 'd_update',
                'contentOptions'=> ['style'=>'text-align:center;'],
                'value' => function($model){
                    return $model->getThaiDate($model->d_update);
                }
            ],
        ],
    ]); ?>

</div>

views/inventory/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Inventory */

$this->title = 'Update Inventory: ' . $model->inventory_id;
$this->params['breadcrumbs'][] = ['label' => 'Inventories', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->inventory_id, 'url' => ['view', 'id' => $model->inventory_id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="inventory-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/inventory/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Inventory */

$this->title = $model->inventory_id;
$this->params['breadcrumbs'][] = ['label' => 'Inventories', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="inventory-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->inventory_id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->inventory_id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'inventory_id',
            'item_id',
            'stock_id',
            'remain',
            'user_id',
            'd_update',
        ],
    ]) ?>

</div>