models/Req.php
<?php

namespace app\models;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "req".
 *
 * @property int $req_id
 * @property int $item_id
 * @property int $stock_id
 * @property string $req_date
 * @property int $qty
 * @property string|null $cause
 * @property int $status_id
 * @property string|null $d_update
 */
class Req extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    const PENDING = '1';
    const COMPLETE = '2';
    const DONE = '3';
    const INCOMPLETE = '4';
    const RECIEVE = '5';

    public static function tableName()
    {
        return 'req';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['item_id', 'stock_id', 'req_date', 'qty', 'status_id'], 'required'],
            [['item_id', 'stock_id', 'qty', 'status_id'], 'integer'],
            [['req_date', 'd_update'], 'safe'],
            [['cause'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'req_id' => 'เลขที่',
            'item_id' => 'รายการ',
            'stock_id' => 'ผู้ขอเบิก',
            'req_date' => 'วันที่ขอเบิก',
            'qty' => 'จำนวน',
            'cause' => 'หมายเหตุ',
            'status_id' => 'สถานะ',
            'd_update' => 'วันที่ปรับปรุง',
        ];
    }

    public function getItem()
    {
        return $this->hasOne(Item::className(), ['item_id' => 'item_id']);
    }

    public function getStock()
    {
        return $this->hasOne(Stock::className(), ['stock_id' => 'stock_id']);
    }

    public static function itemsAlias($key)
    {

        $items = [
            'status' => [
                self::PENDING => 'ขอเบิก',
                self::COMPLETE => 'ตัดจ่ายครบถ้วน',
                self::DONE => 'รับเข้าทัั้งหมด',
                self::INCOMPLETE => 'ตัดจ่ายบางส่วน',
                self::RECIEVE => 'รับเข้าบางส่วน'
            ],
        ];
        return ArrayHelper::getValue($items, $key, []);
        //return array_key_exists($key, $items) ? $items[$key] : [];
    }

    public function getItemStatus()
    {
        return self::itemsAlias('status');
    }

    public function getStatusName(){
        return ArrayHelper::getValue($this->getItemSex(),$this->status_id);
    }
    
}

controllers/DespendController.php
<?php

namespace app\controllers;

use app\models\AddStock;
use Yii;
use app\models\Despend;
use app\models\DespendSearch;
use app\models\Req;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\Inventory;

/**
 * DespendController implements the CRUD actions for Despend model.
 */
class DespendController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Despend models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new DespendSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        if(Yii::$app->user->identity->role == 2 ) {
            $dataProvider->query->where(['stock_id' => Yii::$app->user->identity->profile->stock_id]);
        }

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Despend model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Despend model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($req_id)
    {
        $req = Req::findOne($req_id);

        $model = new Despend();
        $model->stock_id = Yii::$app->user->identity->profile->stock_id;
        if ($req) {
            $model->item_id = $req->item_id;
            $model->to_stock = $req->stock_id;
            $model->req_id = $req->req_id;
            $model->qty = $req->qty;
            $inv = Inventory::find()->where(['item_id' => $model->item_id, 'stock_id' => $model->stock_id])->one();
        }

        if ($model->load(Yii::$app->request->post())) {
            $inv = Inventory::find()->where(['item_id' => $model->item_id, 'stock_id' => $model->stock_id])->one();
            if ($inv->remain >= $model->qty) {
                $model->status_id = '2';
                if ($model->save()) {
                    $inv->remain = $inv->remain - $model->qty;
                    $inv->save();

                    $add = new AddStock();
                    $add->stock_id = $model->to_stock;
                    $add->item_id = $model->item_id;
                    $add->add_date = $model->despend_date;
                    $add->user_id = Yii::$app->user->identity->id;
                    $add->qty = $model->qty;
                    $add->status_id = '1';
                    $add->save();

                    return $this->redirect(['req/index']);
                }
            } else {
                $model->qty = $inv->remain;
                $model->status_id = '4';
                if ($model->save()) {
                    $inv->remain = 0;
                    $inv->save();

                    $add = new AddStock();
                    $add->stock_id = $model->to_stock;
                    $add->item_id = $model->item_id;
                    $add->add_date = $model->despend_date;
                    $add->user_id = Yii::$app->user->identity->id;
                    $add->qty = $model->qty;
                    $add->status_id = '1';
                    $add->save();

                    return $this->redirect(['req/index']);
                }
            }
        }

        return $this->render('create', [
            'model' => $model,
            'inv' => $inv,
        ]);
    }

    public function actionDispend($inv_id)
    {
        $inv = Inventory::findOne($inv_id);

        $model = new Despend();
        $model->stock_id = Yii::$app->user->identity->profile->stock_id;
        $model->item_id = $inv->item_id;
        $model->to_stock = 0;
        $model->req_id = 0;

        if ($model->load(Yii::$app->request->post())) {
            if ($inv->remain >= $model->qty) {
                $model->status_id = '2';
                if ($model->save()) {
                    $inv->remain = $inv->remain - $model->qty;
                    $inv->save();

                    return $this->redirect(['inventory/index']);
                }
            } else {
                $model->qty = $inv->remain;
                $model->status_id = '4';
                if ($model->save()) {
                    $inv->remain = 0;
                    $inv->save();

                    return $this->redirect(['inventory/index']);
                }
            }
        }

        return $this->render('update', [
            'model' => $model,
            'inv' => $inv,
        ]);
    }


    /**
     * Updates an existing Despend model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->despend_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Despend model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Despend model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Despend the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Despend::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/ReqController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Req;
use app\models\ReqSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ReqController implements the CRUD actions for Req model.
 */
class ReqController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Req models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ReqSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        if(Yii::$app->user->identity->role == 2){
            $dataProvider->query->where(['stock_id'=>Yii::$app->user->identity->profile->stock_id]);
        }

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Req model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Req model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($item_id)
    {
        $model = new Req();
        $model->item_id = $item_id;
        $model->stock_id = Yii::$app->user->identity->profile->stock_id;
        $model->status_id = '1';

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['inventory/list', 'id' => $model->stock_id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Req model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->req_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Req model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Req model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Req the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Req::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/req/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\date\DatePicker;

/* @var $this yii\web\View */
/* @var $model app\models\Req */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="req-form">

    <?php $form = ActiveForm::begin(); ?>
    <div class="row">
        <div class="col-md-4">
            <?= $form->field($model, 'req_date')->widget(
                DatePicker::ClassName(),
                [
                    'name' => 'วันที่ขอเบิก',
                    'type' => DatePicker::TYPE_COMPONENT_APPEND,
                    'options' => ['placeholder' => 'ระบุวัน'],
                    'pluginOptions' => [
                        'format' => 'yyyy-mm-dd',
                        'todayHighlight' => true
                    ]
                ]
            );
            ?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'qty')->textInput() ?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'cause')->textInput(['maxlength' => true]) ?>
        </div>
    </div>
    <div class="form-group">
        <?= Html::submitButton('ส่งรายการคำขอเบิก', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/req/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ReqSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="req-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'req_id') ?>

    <?= $form->field($model, 'item_id') ?>

    <?= $form->field($model, 'stock_id') ?>

    <?= $form->field($model, 'req_date') ?>

    <?= $form->field($model, 'qty') ?>

    <?php // echo $form->field($model, 'cause') ?>

    <?php // echo $form->field($model, 'status_id') ?>

    <?php // echo $form->field($model, 'd_update') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/req/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Req */

$this->title = 'ขอเบิกเวชภัณฑ์มิใช่ยา';
$this->params['breadcrumbs'][] = ['label' => 'ทะเบียนรายการขอเบิก', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="req-create">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/req/index.php
<?php

use yii\bootstrap4\Html;
// use yii\grid\GridView;
use kartik\grid\GridView;
use kartik\icons\Icon;

use app\models\Inventory;
Icon::map($this);

/* @var $this yii\web\View */
/* @var $searchModel app\models\ReqSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Reqs';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="req-index">

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'panel' => [
            'heading' => "รายการเวชภัณฑ์มิใช่ยา",
            'before' => ' ',
            'type' => \kartik\grid\GridView::TYPE_SUCCESS,
        ],
        // 'filterModel' => $searchModel,
        'columns' => [
            //['class' => 'yii\grid\SerialColumn'],
            [
                'class' => 'yii\grid\ActionColumn',
                'header' => 'ตัดจ่าย',
                'options' => ['style' => 'width:50px;'],
                'buttonOptions' => ['class' => 'btn btn-primary btn-sm'],
                'template' => '{despend}',
                'buttons' => [
                    'despend' => function ($url, $model, $key) {
                        return Html::a(Icon::show('fa fa-dolly'), ['despend/create', 'req_id' => $model->req_id], ['class' => 'btn btn-danger', 'style' => ['width' => '50px']]);
                    }
                ]
            ],
            'req_id',
            [
                'attribute' => 'stock_id',
                'headerOptions' => ['style' => 'width:20%'],
                'value' => function($model){
                    return $model->stock->stock_name;
                }
            ],
            [
                'attribute' => 'req_date',
                'contentOptions'=> ['style'=>'text-align:center;'],
                'value' => function($model){
                    return Inventory::getThaiDate($model->req_date);
                }
            ],
            [
                'attribute' => 'item_id',
                'headerOptions' => ['style' => 'width:30%'],
                'value' => function($model){
                    return $model->item->item_name;
                }
            ],
            [
                'attribute' => 'qty',
                'contentOptions'=> ['style'=>'text-align:center;'],
                'value' => function($model){
                    return number_format($model->qty);
                }
            ],
            'status_id',
            [
                'attribute' => 'd_update',
                'contentOptions'=> ['style'=>'text-align:center;'],
                'value' => function($model){
                    return Inventory::getThaiDate($model->d_update);
                }
            ],
            'cause',
        ],
    ]); ?>


</div>

views/req/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Req */

$this->title = 'Update Req: ' . $model->req_id;
$this->params['breadcrumbs'][] = ['label' => 'Reqs', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->req_id, 'url' => ['view', 'id' => $model->req_id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="req-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/req/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Req */

$this->title = $model->req_id;
$this->params['breadcrumbs'][] = ['label' => 'Reqs', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="req-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->req_id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->req_id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'req_id',
            'item_id',
            'stock_id',
            'req_date',
            'qty',
            'cause',
            'status_id',
            'd_update',
        ],
    ]) ?>

</div>